---
title: "DS Minor: visNetwork "
output: 
  html_document: 
    code_folding: show
    theme: cosmo
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(igraph)
# library(ggraph)
library(visNetwork)

?goldfish::Social_Evolution

load('~/shared/minor2_2021/2-tm-net/lab03-visualization/Social_Evolution.RData')
```

### Documentation

```{r}
visDocumentation()
vignette("Introduction-to-visNetwork")
shiny::runApp(system.file("shiny", package = "visNetwork"))
```

### Minimal Example

```{r}
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3))

visNetwork(nodes , edges, width = "100%")
?visNetwork
```

```{r}
nodes <- data.frame(id = actors$label)
edges <- data.frame(from = calls$sender, to = calls$receiver)

# visNetwork(nodes, edges, width = "100%")%>%
visNetwork(nodes, edges, width = "100%") %>% 
 visPhysics(solver = "forceAtlas2Based")

visNetwork(nodes, edges, width = "100%") %>% 
 visPhysics(solver = "forceAtlas2Based")%>%
  visPhysics(stabilization = FALSE)
```

### Groups

```{r}
nodes <- data.frame(id = actors$label,
                    group = actors$gradeType)


visNetwork(nodes, edges, width = "100%") %>% 
 visPhysics(solver = "forceAtlas2Based")
```

```{r}
visNetwork(nodes, edges, width = "100%") %>%
  visPhysics(solver = "forceAtlas2Based") %>%
  visGroups(
    groupname = "1",
    color = "turquoise",
    shape = "square",
    shadow = list(enabled = TRUE)
  )
?visGroups
```

## Edges

```{r}
visNetwork(nodes, edges, width = "100%") %>%
  visPhysics(solver = "forceAtlas2Based") %>% 
  visEdges(shadow = TRUE,
           arrows =list(to = list(enabled = TRUE, scaleFactor = 1)),
           color = list(color = "lightblue", highlight = "black"))
```

### weighted

```{r}
# nodes <- data.frame(id = actors$label)
calls %>%
  count(sender, receiver) %>%
  rename(value = n) -> calls_weighted

calls_weighted %>% head()

edges <-
  data.frame(
    from = calls_weighted$sender,
    to = calls_weighted$receiver,
    # value =  calls_weighted$value,
    value =  log(calls_weighted$value) + 0.1,
    title = str_c("calls:", calls_weighted$value)
  )


visNetwork(nodes, edges, width = "100%")
```

### night and day

```{r}
calls %>%
  mutate(time  = time %>% lubridate::as_datetime()) %>% 
  mutate(day = case_when(
    time %>% lubridate::hour() >= 22 ~ 'darkblue',
    time %>% lubridate::hour() <= 8 ~ 'darkblue',
    T ~ 'yellow'
    )) -> calls_time

edges <-
  data.frame(
    from = calls_time$sender,
    to = calls_time$receiver,
    color =  calls_time$day
  )

visNetwork(nodes, edges, width = "100%")
```


### Legend

```{r}
visNetwork(nodes, edges, width = "100%",  main = "Network of phone calls") %>% 
    visPhysics(solver = "repulsion") %>% 
visLegend(
  width = 0.1,
  position = "right"
) 
```

## Aditional stuff

### Select nodes

```{r}
visNetwork(nodes, edges, width = "100%",  main = "Network of phone calls") %>% 
visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE) %>%
  visPhysics(solver = "repulsion") %>% 
  visEdges(shadow = F,
           arrows =list(to = list(enabled = TRUE, scaleFactor = 1)),
           color = list(color = "lightblue", highlight = "black")) %>% 
    visOptions(selectedBy = "group")
?visOptions
```

## from igraph


```{r}

?toVisNetworkData
test <- as.matrix(read.table(header = FALSE, text = "
    0    1    3    7    1
    4    0    8    9    5
   10    3    0    8    3
    5    1    5    0    7
    8    2    7    4    0"))

test.gr <- graph_from_adjacency_matrix(test, mode="undirected", weighted=T)
plot(test.gr)

test.visn <- toVisNetworkData(test.gr)

test.visn$edges$value <- test.visn$edges$weight

visNetwork(test.visn$nodes, test.visn$edges) %>%
  visIgraphLayout(layout = "layout_in_circle") 
```


```{r}
?visIgraphLayout

visNetwork(nodes, edges, width = "100%",  main = "Network of phone calls") %>% 
visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE) %>%
  # visPhysics(solver = "repulsion") %>% 
  visIgraphLayout(layout = "layout_nicely")

?visIgraphLayout
```

## Freze

```{r}
visNetwork(nodes, edges, width = "100%",  main = "Network of phone calls, frozen") %>% 
visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE) %>%
  visPhysics(solver = "repulsion") %>% 
  # visIgraphLayout(layout = "layout_nicely") %>% 
    visInteraction(dragNodes = FALSE, dragView = FALSE, zoomView = FALSE)
```


### Images

```{r}
nodes <- data.frame(id = 1:4, 
                    shape = c("image", rep("circularImage", 3)),
                    image = c(
                      "https://www.r-project.org/Rlogo.png",
                      'https://developer.r-project.org/Logo/Rlogo-1.png',
                      'https://developer.r-project.org/Logo/Rlogo-1.png',
                      'https://developer.r-project.org/Logo/Rlogo-1.png'
                    ), 
                    label = c('you' ,rep("project", 3)))
  
edges <- data.frame(from = c(1,1,1), to = c(2,3,4))

visNetwork(nodes, edges, width = "100%") %>% 
  visNodes(shapeProperties = list(useBorderWithImage = TRUE)) %>%
  visLayout(randomSeed = 2)
```


